colors = [
    ["Aged Copper", "Aged-Copper", "Aged Copper", "aged copper", "aged-copper", "aged copper"],
    ["Ash Gray", "Ash-Gray", "Ash Gray", "ash gray", "ash-gray", "ash gray"],
    ["Black", "Black", "black"],
    ["Bone White", "Bone-White", "Bone White", "bone white", "bone-white"],
    ["Bright Yellow", "Bright-Yellow", "Bright Yellow", "bright yellow", "bright-yellow"],
    ["Buckskin", "Buckskin", "buckskin"],
    ["Burgundy", "Burgundy", "burgundy"],
    ["Burnished Slate", "Burnished-Slate", "Burnished Slate", "burnished slate", "burnished-slate"],
    ["Carmelized", "Carmelized", "carmelized"],
    ["Champagne", "Champagne", "champagne"],
    ["Charcoal Grey", "Charcoal-Grey", "Charcoal Grey", "charcoal grey", "charcoal-grey"],
    ["Colonial Red", "Colonial-Red", "Colonial Red", "colonial red", "colonial-red"],
    ["Copper Metallic", "Copper-Metallic", "Copper Metallic", "copper metallic", "copper-metallic"],
    ["Copper-Ten Raw", "Copper-Ten-Raw", "Copper-Ten Raw", "copper-ten raw", "copper-ten-raw"],
    ["Cor-Ten AZP Raw", "Cor-Ten-AZP-Raw", "Cor-Ten AZP Raw", "cor-ten azp raw", "cor-ten-azp-raw"],
    ["Custom Black/Gray", "Custom-Black/Gray", "Custom Black/Gray", "custom black/gray", "custom-black/gray"],
    ["Custom Silver", "Custom-Silver", "Custom Silver", "custom silver", "custom-silver"],
    ["Custom Slate Gray", "Custom-Slate-Gray", "Custom Slate Gray", "custom slate gray", "custom-slate-gray"],
    ["Dark Bronze", "Dark-Bronze", "Dark Bronze", "dark bronze", "dark-bronze"],
    ["Dark Gray", "Dark-Gray", "Dark Gray", "dark gray", "dark-gray"],
    ["Dove Gray", "Dove-Gray", "Dove Gray", "dove gray", "dove-gray"],
    ["Dromedary Camel", "Dromedary-Camel", "Dromedary Camel", "dromedary camel", "dromedary-camel"],
    ["East Georgia Green", "East-Georgia-Green", "East Georgia Green", "east georgia green", "east-georgia-green"],
    ["Evergreen", "Evergreen", "evergreen"],
    ["Facebook Gray", "Facebook-Gray", "Facebook Gray", "facebook gray", "facebook-gray"],
    ["Frank Blue", "Frank-Blue", "Frank Blue", "frank blue", "frank-blue"],
    ["Galv-Ten Raw", "Galv-Ten-Raw", "Galv-Ten Raw", "galv-ten raw", "galv-ten-raw"],
    ["Galvalume Plus", "Galvalume-Plus", "Galvalume Plus", "galvalume plus", "galvalume-plus"],
    ["Hang 10 Blue", "Hang-10-Blue", "Hang 10 Blue", "hang 10 blue", "hang-10-blue"],
    ["Hartford Green", "Hartford-Green", "Hartford Green", "hartford green", "hartford-green"],
    ["Hemlock Green", "Hemlock-Green", "Hemlock Green", "hemlock green", "hemlock-green"],
    ["Kawneer Charcoal", "Kawneer-Charcoal", "Kawneer Charcoal", "kawneer charcoal", "kawneer-charcoal"],
    ["Mansard Brown", "Mansard-Brown", "Mansard Brown", "mansard brown", "mansard-brown"],
    ["Matte Black", "Matte-Black", "Matte Black", "matte black", "matte-black"],
    ["Medium Bronze", "Medium-Bronze", "Medium Bronze", "medium bronze", "medium-bronze"],
    ["Mill Finish", "Mill-Finish", "Mill Finish", "mill finish", "mill-finish"],
    ["Miscellaneous", "Miscellaneous", "miscellaneous"],
    ["Old Gold Bronze", "Old-Gold-Bronze", "Old Gold Bronze", "old gold bronze", "old-gold-bronze"],
    ["Paint Grip (Bonderize)", "Paint-Grip-(Bonderize)", "Paint Grip (Bonderize)", "paint grip (bonderize)", "paint-grip-(bonderize)"],
    ["Patina Green", "Patina-Green", "Patina Green", "patina green", "patina-green"],
    ["Porsche Targa Black", "Porsche-Targa-Black", "Porsche Targa Black", "porsche targa black", "porsche-targa-black"],
    ["PreWeathered Galvalume", "PreWeathered-Galvalume", "PreWeathered Galvalume", "preweathered galvalume", "preweathered-galvalume"],
    ["Regal Blue", "Regal-Blue", "Regal Blue", "regal blue", "regal-blue"],
    ["Regal Red", "Regal-Red", "Regal Red", "regal red", "regal-red"],
    ["Regal White", "Regal-White", "Regal White", "regal white", "regal-white"],
    ["Sandstone", "Sandstone", "sandstone"],
    ["Seal Brown", "Seal-Brown", "Seal Brown", "seal brown", "seal-brown"],
    ["SECU Charcoal Grey", "SECU-Charcoal-Grey", "SECU Charcoal Grey", "secu charcoal grey", "secu-charcoal-grey"],
    ["Sierra Tan", "Sierra-Tan", "Sierra Tan", "sierra tan", "sierra-tan"],
    ["Silver Metallic", "Silver-Metallic", "Silver Metallic", "silver metallic", "silver-metallic"],
    ["Slate Blue", "Slate-Blue", "Slate Blue", "slate blue", "slate-blue"],
    ["Slate Gray", "Slate-Gray", "Slate Gray", "slate gray", "slate-gray"],
    ["Stone White", "Stone-White", "Stone White", "stone white", "stone-white"],
    ["Surrey Beige", "Surrey-Beige", "Surrey Beige", "surrey beige", "surrey-beige"],
    ["Teal", "Teal", "teal"],
    ["Terra Cotta", "Terra-Cotta", "Terra Cotta", "terra cotta", "terra-cotta"],
    ["Textured Low Gloss Black", "Textured-Low-Gloss-Black", "Textured Low Gloss Black", "textured low gloss black", "textured-low-gloss-black"],
    ["Textured Low Gloss Charcoal Grey", "Textured-Low-Gloss-Charcoal-Grey", "Textured Low Gloss Charcoal Grey", "textured low gloss charcoal grey", "textured-low-gloss-charcoal-grey"],
    ["Textured Low Gloss Dark Bronze", "Textured-Low-Gloss-Dark-Bronze", "Textured Low Gloss Dark Bronze", "textured low gloss dark bronze", "textured-low-gloss-dark-bronze"],
    ["Textured Low Gloss Moonstone", "Textured-Low-Gloss-Moonstone", "Textured Low Gloss Moonstone", "textured low gloss moonstone", "textured-low-gloss-moonstone"],
    ["Vintage", "Vintage", "vintage"]
]
